### ISSUE TITLE
Add task with buttons into the to-do list

### ISSUE THREAD

**Issue by samahjamie** [GSG-CF04/ToDoList_04#10]
- [x] Add edit button.
- [x] Add check button.
- [x] Add delete button.
